name: Microsoft Teams Notification

on:
  push:
    branches:
      - main
    paths:
      - '**/tests/**'

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Notification to Microsoft Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d '{"text": "GitHubissa tehty muutoksia (push event)"}' -X POST $TEAMS_WEBHOOK_URL

  simple-robot-test:
    runs-on: ubuntu-latest
    if: startsWith(github.event_path, 'tests/')

    steps: 
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework

      - name: Run Robot Test
        run: robot -d 2024-Q1-pilvipalvelut/week5/robot/results 2024-Q1-pilvipalvelut/week5/robot
        