name: Microsoft Teams Notification

on:
  push:
    branches:
      - main
      
jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Notification to Microsoft Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d '{"text": "GitHubissa tehty muutoksia (push event)"}' -X POST $TEAMS_WEBHOOK_URL